services:
  - type: web
    name: order-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_app.py
    envVars:
      # 数据库配置 - 使用Render PostgreSQL
      - key: DATABASE_URL
        fromDatabase:
          name: order-management-db
          property: connectionString
    envVars:
      # Python版本配置
      - key: PYTHON_VERSION
        value: 3.11.5
      
      # Flask应用配置
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: false
      - key: SECRET_KEY
        value: f7e3f65dcf0d3e6da4b96b75e686aeffd9db86f5acd41c3ecfcca25239e57b61
      
      # 数据库配置 - 使用Render PostgreSQL
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: false
      
      # 邮件配置 - Gmail (推荐用于生产环境)
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: true
      - key: MAIL_USE_SSL
        value: false
      - key: MAIL_USERNAME
        value: nunalinks@gmail.com
      - key: MAIL_PASSWORD
        value: davh hlya mout oosq
      
      # 应用配置
      - key: BASE_URL
        value: https://your-app-name.onrender.com
      - key: ITEMS_PER_PAGE
        value: 20
      - key: MAX_CONTENT_LENGTH
        value: 16777216
      
      # 安全配置
      - key: WTF_CSRF_ENABLED
        value: true
      - key: WTF_CSRF_SECRET_KEY
        value: a764d876752e9cb4e962f07aa6616cf0c293ba1fe26966df35a3de992d1c2b97
      
      # 日志配置
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_TO_STDOUT
        value: true

  # PostgreSQL数据库服务
  - type: pserv
    name: order-management-db
    env: postgresql
    plan: free
    ipAllowList: [] 