services:
  - type: web
    name: order-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0 